language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 1.0.0-preview2-1-003177
before_script:
  - cd Platform
  - dotnet restore
script:  
  - cd Platform
  - cd Platform.Tests
  - dotnet test 
